version: "2.1"

services:
  nightowl:
    build: ./
    mem_limit: 1028m
    ports:
      - "44444:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=local
    depends_on:
      - postgres

  postgres:
    image: postgres:9.6-alpine
    ports:
      - "5432:5432"
    environment:
      - 'POSTGRES_ROOT_PASSWORD=postgres'
      - 'POSTGRES_USER=postgres'
      - 'POSTGRES_PASSWORD=postgres'
      - 'POSTGRES_DB=nightowl'